using System.Collections.Generic;

namespace FiveMenu.Client
{
    internal class Data
    {
        public static string[,][] vehicleList =
            {
                {
                    new string[] { "Mercedes" },
                    new string[] {
                        "E55 W211",
                        "C63 S Coupe W205",
                        "CL63 AMG",
                        "E63 AMG",
                        "S63 W222",
                        "S63 W221",
                        "Benz Actros",
                        "Maybach MR 500",
                        "E400 4Matic",
                        "AMG GTR R20",
                        "A45 AMG",
                        "A45 S AMG",
                        "Brabus 850",
                        "CLS 63",
                        "CLS 53",
                        "E63 S AMG 4Matic",
                        "G500",
                        "GLE 53",
                        "GLS 63",
                        "C63 AMG W204",
                        "McLaren 722 S",
                        "S65 AMG W220"
                    },
                    new string[] {
                        "benze55",
                        "c63s",
                        "cl63amg",
                        "e63amg",
                        "s63w222",
                        "w221s63",
                        "actros",
                        "oycmr500",
                        "e400",
                        "amggtrr20",
                        "a45amg",
                        "gxa45",
                        "brabus850",
                        "cls2015",
                        "cls53",
                        "e63s",
                        "g500",
                        "gle53",
                        "gls63",
                        "c63w204",
                        "722s",
                        "s65amg"
                    },
                },
                {
                    new string[] { "BMW" },
                    new string[] {
                        "M760i V12",
                        "i8",
                        "M5 F90",
                        "M8",
                        "E60 V10",
                        "M3 E30",
                        "M3 E36",
                        "M3 F80",
                        "M5 F10",
                        "M6 GC",
                        "M4 GTS",
                        "X6M",
                        "M6 F13",
                        "M5 Competition",
                        "X5 E53",
                        "M4 Competition"
                    },
                    new string[] {
                        "17m760i",
                        "acs8",
                        "bmci",
                        "bmwm8",
                        "e60",
                        "m3e30",
                        "m3e36",
                        "m3f80",
                        "m5f10",
                        "m6gc",
                        "rmodm4gts",
                        "x6m",
                        "m6f13",
                        "2019M5",
                        "x5e53",
                        "m422"
                    },
                },
                {
                    new string[] { "Audi" },
                    new string[] {
                        "R8 V10 Plus",
                        "RS7",
                        "RS6",
                        "A4 Quattro ABT",
                        "A8 L W12",
                        "A8 FSI",
                        "RS3 Sportback",
                        "RS5",
                        "RS7 2021",
                        "RS Q8 M"
                    },
                    new string[] {
                        "r820",
                        "rs7",
                        "rs62",
                        "aaq4",
                        "a8lw12",
                        "a8fsi",
                        "rs318",
                        "rs5",
                        "rs721",
                        "rsq8m"
                    },
                },
                {
                    new string[] { "Porsche" },
                    new string[] { "911 Turbo S", "Cayenne S18", "Panamera 17 Turbo", "Taycan" },
                    new string[] { "911turbos", "pcs18", "panamera17turbo", "taycan" },
                },
                {
                    new string[] { "Ferrari" },
                    new string[] { "599 GTO", "La Ferrari", "F8 Spider Tributo", "Portofino" },
                    new string[] { "599gto", "laferrari", "f8t", "fpino" },
                },
                {
                    new string[] { "Lamborghini" },
                    new string[] { "LP 700R", "Urus", "Aventador", "LP 670 SV" },
                    new string[] { "lp700r", "urus2018", "aventador", "lp670sv" },
                },
                {
                    new string[] { "Bentley" },
                    new string[] { "Bentayga 2017", "Continental GT", "Mulsanne" },
                    new string[] { "bentayga17", "bcgt", "bmm" },
                },
                {
                    new string[] { "Volkswagen" },
                    new string[] { "Golf 75R", "MK3 VR6", "Touareg R50" },
                    new string[] { "golf75r", "mk3vr6", "r50" },
                },
                {
                    new string[] { "Toyota" },
                    new string[] { "Camry", "Supra 80" },
                    new string[] { "camry55", "a80" },
                },
                {
                    new string[] { "Cadillac" },
                    new string[] { "ATS", "CTS 350T" },
                    new string[] { "cats", "ct5v" },
                },
                {
                    new string[] { "Bugatti" },
                    new string[] { "Veyron Supersport", "Divo" },
                    new string[] { "supersport", "divo" },
                },
                {
                    new string[] { "Ford" },
                    new string[] { "Focus RS", "Expedition Max" },
                    new string[] { "focusrs", "expmax20" },
                },
                {
                    new string[] { "Range Rover" },
                    new string[] { "Velar", "SVR Mansory" },
                    new string[] { "18Velar", "mansrr" },
                },
                {
                    new string[] { "Rolls Royce" },
                    new string[] { "Wraith", "Cullinan" },
                    new string[] { "wraith", "rculi" },
                },
                {
                    new string[] { "Nissan" },
                    new string[] { "GTR R35", "Titan 17" },
                    new string[] { "gtr", "titan17" },
                },
                {
                    new string[] { "Renault" },
                    new string[] { "Clio RS" },
                    new string[] { "cliors" },
                },
                {
                    new string[] { "Pagani" },
                    new string[] { "Huayra" },
                    new string[] { "huayra" },
                },
                {
                    new string[] { "Koenigsegg" },
                    new string[] { "Jesko" },
                    new string[] { "jesko2020" },
                },
                {
                    new string[] { "Lexus" },
                    new string[] { "LX" },
                    new string[] { "lx2018" },
                },
                {
                    new string[] { "Mitsubishi" },
                    new string[] { "EVO 10" },
                    new string[] { "evo10" },
                },
                {
                    new string[] { "Tesla" },
                    new string[] { "Model 3" },
                    new string[] { "tmodel" },
                },
                {
                    new string[] { "Jeep" },
                    new string[] { "SRT8" },
                    new string[] { "srt8" },
                },
                {
                    new string[] { "Bikes" },
                    new string[] { "Kawasaki Ninja H2R", "Yamaha YZF-R1" },
                    new string[] { "nh2r", "r1" },
                },
                {
                    new string[] { "Planes | Helicopters" },
                    new string[] { "Airbus A350", "Lockheed Martin F-22 Raptor", "McDonnell Douglas F/A-18 Hornet", "Sikorsky MH-53 Pave Low" },
                    new string[] { "a350", "f22a", "hornet", "pavelow" },
                },
                {
                    new string[] { "Police Cars" },
                    new string[] { "Porsche 718", "Lamborghini LP770", "McLaren P1", "Bugatti Veyron Supersport" },
                    new string[] { "pol718", "pollp770", "polp1", "polveyron" },
                },
                {
                    new string[] { "Base Game Vehicles" },
                    new string[] {
                        "9F",
                        "9F Cabrio",
                        "Blista",
                        "Asea",
                        "Asea",
                        "Boat Trailer",
                        "Bus",
                        "Army Trailer",
                        "Army Trailer",
                        "Army Trailer",
                        "Freight Trailer",
                        "Dashound",
                        "Airport Bus",
                        "Asterope",
                        "Airtug",
                        "Ambulance",
                        "Barracks",
                        "Barracks Semi",
                        "Baller",
                        "Baller",
                        "BeeJay XL",
                        "Banshee",
                        "Benson",
                        "Injection",
                        "Biff",
                        "Blazer",
                        "Blazer Lifeguard",
                        "Hot Rod Blazer",
                        "Bison",
                        "Bison",
                        "Bison",
                        "Boxville",
                        "Boxville",
                        "Boxville",
                        "Bobcat XL",
                        "Bodhi",
                        "Buccaneer",
                        "Buffalo",
                        "Buffalo S",
                        "Dozer",
                        "Bullet",
                        "Atomic Blimp",
                        "Burrito",
                        "Bugstars Burrito",
                        "Burrito",
                        "Burrito",
                        "Burrito",
                        "Cavalcade",
                        "Cavalcade",
                        "Police Transporter",
                        "Gang Burrito",
                        "Cable Car",
                        "Caddy",
                        "Caddy",
                        "Camper",
                        "Carbonizzare",
                        "Cheetah",
                        "Comet",
                        "Cognoscenti Cabrio",
                        "Coquette",
                        "Cutter",
                        "Gresley",
                        "Dilettante",
                        "Dilettante",
                        "Dune Buggy",
                        "Space Docker",
                        "Hotknife",
                        "Duneloader",
                        "Dubsta",
                        "Dubsta",
                        "Dump",
                        "Rubble",
                        "Docktug",
                        "Dominator",
                        "Emperor",
                        "Emperor",
                        "Emperor",
                        "Entity XF",
                        "Exemplar",
                        "Elegy RH8",
                        "F620",
                        "FIB",
                        "FIB",
                        "Felon",
                        "Felon GT",
                        "Feltzer",
                        "Fire Truck",
                        "Flatbed",
                        "Forklift",
                        "FQ 2",
                        "Fusilade",
                        "Fugitive",
                        "Futo",
                        "Granger",
                        "Gauntlet",
                        "Habanero",
                        "Hauler",
                        "Dock Handler",
                        "Infernus",
                        "Ingot",
                        "Intruder",
                        "Issi",
                        "JackalJackal",
                        "Journey",
                        "JB 700",
                        "Khamelion",
                        "Landstalker",
                        "Lifeguard",
                        "Manana",
                        "Mesa",
                        "Mesa",
                        "Mesa",
                        "Crusader",
                        "Minivan",
                        "Mixer",
                        "Mixer",
                        "Monroe",
                        "Lawn Mower",
                        "Mule",
                        "Mule",
                        "Oracle XS",
                        "Oracle",
                        "Packer",
                        "Patriot",
                        "Prison Bus",
                        "Penumbra",
                        "Peyote",
                        "Phantom",
                        "Phoenix",
                        "Picador",
                        "Pounder",
                        "Police Cruiser",
                        "Unmarked Cruiser",
                        "Police Cruiser",
                        "Police Cruiser",
                        "Police Rancher",
                        "Police Roadcruiser",
                        "Pony",
                        "Pony",
                        "Prairie",
                        "Park Ranger",
                        "Premier",
                        "Primo",
                        "Prop Trailer",
                        "Rancher XL",
                        "Rancher XL",
                        "Rapid GT",
                        "Rapid GT",
                        "Radius",
                        "Rat-Loader",
                        "Rusty Rebel",
                        "Regina",
                        "Rebel",
                        "Rental Shuttle Bus",
                        "Ruiner",
                        "Rumpo",
                        "Rumpo",
                        "Rhino Tank",
                        "Police Riot",
                        "Ripley",
                        "Rocoto",
                        "Romero Hearse",
                        "Sabre Turbo",
                        "Sadler",
                        "Sadler",
                        "Sandking XL",
                        "Sandking SWB",
                        "Schafter",
                        "Schwartzer",
                        "Scrap Truck",
                        "Seminole",
                        "Sentinel XS",
                        "Sentinel",
                        "Zion",
                        "Zion Cabrio",
                        "Serrano",
                        "Sheriff Cruiser",
                        "Sheriff SUV",
                        "Speedo",
                        "Clown Van",
                        "Stanier",
                        "Stinger",
                        "Stinger GT",
                        "Stockade",
                        "Stockade",
                        "Stratum",
                        "Sultan",
                        "Super Diamond",
                        "Surano",
                        "Surfer",
                        "Surfer",
                        "Surge",
                        "Taco Van",
                        "Tailgater",
                        "Taxi",
                        "Trashmaster",
                        "Tractor",
                        "Fieldmaster",
                        "Fieldmaster",
                        "Grain Trailer",
                        "Baletrailer",
                        "Tipper",
                        "Tipper",
                        "Tornado",
                        "Tornado",
                        "Tornado",
                        "Tornado",
                        "Tourbus",
                        "Towtruck",
                        "Towtruck",
                        "Utility Truck",
                        "Utility Truck",
                        "Utility Truck",
                        "Voodoo",
                        "Washington",
                        "Stretch",
                        "Youga",
                        "Z-Type",
                        "Sanchez (livery)",
                        "Sanchez",
                        "Scorcher",
                        "Whippet Race Bike",
                        "Endurex Race Bike",
                        "Tri-Cycles Race Bike",
                        "Fixter",
                        "Cruiser",
                        "BMX",
                        "Police Bike",
                        "Akuma",
                        "Carbon RS",
                        "Bagger",
                        "Bati 801",
                        "Bati 801RR",
                        "Ruffian",
                        "Daemon",
                        "Double-T",
                        "PCJ 600",
                        "Vader",
                        "Vigero",
                        "Faggio",
                        "Hexer",
                        "Annihilator",
                        "Buzzard Attack Chopper",
                        "Buzzard",
                        "Cargobob",
                        "Cargobob",
                        "Cargobob",
                        "Skylift",
                        "Police Maverick",
                        "Maverick",
                        "Nemesis",
                        "Frogger",
                        "Frogger",
                        "Cuban 800",
                        "Duster",
                        "Mallard",
                        "Mammatus",
                        "Jet",
                        "Shamal",
                        "Luxor",
                        "Titan",
                        "P-996 LAZER",
                        "Cargo Plane",
                        "Squalo",
                        "Marquis",
                        "Dinghy",
                        "Dinghy",
                        "Jetmax",
                        "Police Predator",
                        "Tropic",
                        "Seashark",
                        "Seashark",
                        "Submersible",
                        "Freight Train",
                        "Freight Train",
                        "Freight Train",
                        "Freight Train",
                        "Freight Train",
                        "Freight Train",
                        "Freight Train",
                        "Dock Trailer",
                        "Trailer",
                        "Trailer",
                        "Trailer",
                        "Trailer",
                        "Trailer",
                        "Trailer",
                        "Trailer",
                        "Trailer",
                        "Trailer",
                        "Trailer",
                        "Trailer",
                        "Trailer",
                        "Velum",
                        "Adder",
                        "Voltic",
                        "Vacca",
                        "Suntrap",
                        "Kraken",
                        "Dukes",
                        "Duke O'Death",
                        "Sprunk Buffalo",
                        "Pisswasser Dominator",
                        "Dodo",
                        "Marshall",
                        "Xero Blimp",
                        "Redwood Gauntlet",
                        "Stallion",
                        "Burger Shot Stallion",
                        "Blista Compact",
                        "Go Go Monkey Blista",
                        "Bifta",
                        "Speeder",
                        "Kalahari",
                        "Paradise",
                        "Roosevelt",
                        "Jester",
                        "Turismo R",
                        "Alpha",
                        "Vestra",
                        "Zentorno",
                        "Massacro",
                        "Huntley S",
                        "Thrust",
                        "Rhapsody",
                        "Warrener",
                        "Blade",
                        "Glendale",
                        "Panto",
                        "Dubsta 6x6",
                        "Pigalle",
                        "Liberator",
                        "Sovereign",
                        "Innovation",
                        "Hakuchou",
                        "Furore GT",
                        "Miljet",
                        "Besra",
                        "Coquette Classic",
                        "Swift",
                        "Jester (Racecar)",
                        "Massacro (Racecar)",
                        "Rat-Truck",
                        "Slamvan",
                        "Mule",
                        "Velum 5-Seater",
                        "Tanker",
                        "Casco",
                        "Boxville",
                        "Hydra",
                        "Insurgent Pick-Up",
                        "Insurgent",
                        "Gang Burrito",
                        "Technical",
                        "Dinghy",
                        "Savage",
                        "Enduro",
                        "Guardian",
                        "Lectro",
                        "Kuruma",
                        "Kuruma (Armored)",
                        "Trashmaster",
                        "Barracks",
                        "Valkyrie",
                        "Lost Slamvan",
                        "Swift Deluxe",
                        "Luxor Deluxe",
                        "Stirling GT",
                        "Osiris",
                        "Virgo",
                        "Windsor",
                        "Coquette BlackFin",
                        "Vindicator",
                        "T20",
                        "Brawler",
                        "Toro",
                        "Chino",
                        "Faction",
                        "Faction Custom",
                        "Moonbeam",
                        "Moonbeam Custom",
                        "Primo Custom",
                        "Chino Custom",
                        "Buccaneer Custom",
                        "Voodoo Custom",
                        "Lurcher",
                        "Fr�nken Stange",
                        "Verlierer",
                        "Nightshade",
                        "Mamba",
                        "Turreted Limo",
                        "Schafter V12",
                        "Schafter LWB",
                        "Schafter V12 (Armored)",
                        "Schafter LWB (Armored)",
                        "Cognoscenti 55",
                        "Cognoscenti 55 (Armored)",
                        "Cognoscenti",
                        "Cognoscenti (Armored)",
                        "Baller LE",
                        "Baller LE LWB",
                        "Baller LE (Armored)",
                        "Baller LE LWB (Armored)",
                        "Toro",
                        "Seashark",
                        "Dinghy",
                        "Tropic",
                        "Speeder",
                        "Cargobob",
                        "SuperVolito",
                        "SuperVolito Carbon",
                        "Valkyrie MOD.0",
                        "Tampa",
                        "Sultan RS",
                        "Banshee 900R",
                        "Roosevelt Valor",
                        "Faction Custom Donk",
                        "Minivan Custom",
                        "Sabre Turbo Custom",
                        "Slamvan Custom",
                        "Tornado Custom",
                        "Virgo Classic Custom",
                        "Virgo Classic",
                        "Nimbus",
                        "XLS",
                        "XLS (Armored)",
                        "Seven-70",
                        "FMJ",
                        "Bestia GTS",
                        "811",
                        "Brickade",
                        "Rumpo Custom",
                        "Volatus",
                        "X80 Proto",
                        "Reaper",
                        "Tug",
                        "Windsor Drop",
                        "Lynx",
                        "Gargoyle",
                        "Tyrus",
                        "ETR1",
                        "Omnis",
                        "RE-7B",
                        "Contender",
                        "Trophy Truck",
                        "Desert Raid",
                        "Dune",
                        "Cliffhanger",
                        "BF400",
                        "Tropos Rallye",
                        "Brioso R/A",
                        "Drift Tampa",
                        "Tornado Rat Rod",
                        "Faggio Mod",
                        "Faggio Sport",
                        "Raptor",
                        "Vortex",
                        "Avarus",
                        "Sanctus",
                        "Youga Classic",
                        "Hakuchou Drag",
                        "Nightblade",
                        "Chimera",
                        "Esskey",
                        "Wolfsbane",
                        "Zombie Bobber",
                        "Zombie Chopper",
                        "Defiler",
                        "Daemon",
                        "Rat Bike",
                        "Shotaro",
                        "Manchez",
                        "Street Blazer",
                        "Elegy Retro Custom",
                        "Tempesta",
                        "Itali GTB",
                        "Itali GTB Custom",
                        "Nero",
                        "Nero Custom",
                        "Specter",
                        "Specter Custom",
                        "Diabolus",
                        "Diabolus Custom",
                        "Blazer Aqua",
                        "Ruiner 2000",
                        "Ramp Buggy",
                        "Ramp Buggy",
                        "Phantom Wedge",
                        "Rocket Voltic",
                        "Penetrator",
                        "Armored Boxville",
                        "Wastelander",
                        "Technical Aqua",
                        "FCR 1000",
                        "FCR 1000 Custom",
                        "Comet Retro Custom",
                        "Ruiner",
                        "Turismo Classic",
                        "Infernus Classic",
                        "GP1",
                        "Ruston",
                        "Trailer",
                        "XA-21",
                        "Caddy",
                        "Vagner",
                        "Phantom Custom",
                        "Nightshark",
                        "Cheetah Classic",
                        "Torero",
                        "Hauler Custom",
                        "Mobile Operations Center",
                        "Technical Custom",
                        "Insurgent Pick-Up Custom",
                        "APC",
                        "Weaponized Tampa",
                        "Dune FAV",
                        "Anti-Aircraft Trailer",
                        "Half-track",
                        "Ardent",
                        "Oppressor",
                        "Vigilante",
                        "RM-10 Bombushka",
                        "Alpha-Z1",
                        "Seabreeze",
                        "Tula",
                        "Havok",
                        "FH-1 Hunter",
                        "Ultralight",
                        "Rogue",
                        "Pyro",
                        "Howard NX-25",
                        "Mogul",
                        "LF-22 Starling",
                        "P-45 Nokota",
                        "V-65 Molotok",
                        "Rapid GT Classic",
                        "Retinue",
                        "Cyclone",
                        "Visione",
                        "190z",
                        "Viseris",
                        "Comet SR",
                        "Raiden",
                        "Riata",
                        "SC1",
                        "Autarch",
                        "Savestra",
                        "GT500",
                        "Comet Safari",
                        "Neon",
                        "Sentinel Classic",
                        "TM-02 Khanjali",
                        "Barrage",
                        "Volatol",
                        "Akula",
                        "Deluxo",
                        "Stromberg",
                        "Chernobog",
                        "RCV",
                        "Avenger",
                        "Avenger",
                        "Thruster",
                        "Yosemite",
                        "Hermes",
                        "Hustler",
                        "Streiter",
                        "Revolter",
                        "Pariah",
                        "Kamacho",
                        "Entity XXR",
                        "Cheburek",
                        "Jester Classic",
                        "Caracara",
                        "Hotring Sabre",
                        "Sea Sparrow",
                        "Flash GT",
                        "Ellie",
                        "Michelli GT",
                        "Fagaloa",
                        "Dominator GTX",
                        "Tyrant",
                        "Tezeract",
                        "GB200",
                        "Issi Classic",
                        "Taipan",
                        "Blimp",
                        "Mule Custom",
                        "Pounder Custom",
                        "Speedo Custom",
                        "Festival Bus",
                        "Patriot Stretch",
                        "Swinger",
                        "Terrorbyte",
                        "Oppressor Mk II",
                        "B-11 Strikeforce",
                        "Menacer",
                        "Scramjet",
                        "Freecrawler",
                        "Stafford",
                        "Apocalypse Bruiser",
                        "Future Shock Bruiser",
                        "Nightmare Bruiser",
                        "Apocalypse Brutus",
                        "Future Shock Brutus",
                        "Nightmare Brutus",
                        "Apocalypse Cerberus",
                        "Future Shock Cerberus",
                        "Nightmare Cerberus",
                        "Clique",
                        "Apocalypse Deathbike",
                        "Future Shock Deathbike",
                        "Nightmare Deathbike",
                        "Deveste Eight",
                        "Deviant",
                        "Apocalypse Dominator",
                        "Future Shock Dominator",
                        "Nightmare Dominator",
                        "Impaler",
                        "Apocalypse Impaler",
                        "Future Shock Impaler",
                        "Nightmare Impaler",
                        "Apocalypse Imperator",
                        "Future Shock Imperator",
                        "Nightmare Imperator",
                        "Apocalypse Issi",
                        "Future Shock Issi",
                        "Nightmare Issi",
                        "Itali GTO",
                        "Apocalypse Sasquatch",
                        "Future Shock Sasquatch",
                        "Nightmare Sasquatch",
                        "RC Bandito",
                        "Apocalypse Scarab",
                        "Future Shock Scarab",
                        "Nightmare Scarab",
                        "Schlagen GT",
                        "Apocalypse Slamvan",
                        "Future Shock Slamvan",
                        "Nightmare Slamvan",
                        "Toros",
                        "Tulip",
                        "Vamos",
                        "Apocalypse ZR380",
                        "Future Shock ZR380",
                        "Nightmare ZR380",
                        "Caracara 4x4",
                        "8F Drafter",
                        "Dynasty",
                        "Emerus",
                        "Gauntlet Classic",
                        "Gauntlet Hellfire",
                        "Hellion",
                        "Issi Sport",
                        "Jugular",
                        "Krieger",
                        "Locust",
                        "Paragon R",
                        "Paragon R (Armored)",
                        "Peyote Gasser",
                        "Nebula Turbo",
                        "Neo",
                        "Novak",
                        "Rampant Rocket",
                        "S80RR",
                        "Thrax",
                        "Zion Classic",
                        "Zorrusso",
                        "Asbo",
                        "R88",
                        "PR4",
                        "Furia",
                        "Imorgon",
                        "JB 700W",
                        "Blista Kanjo",
                        "Komoda",
                        "Invade and Persuade Tank",
                        "Outlaw",
                        "Rebla GTS",
                        "Retinue Mk II",
                        "Stryder",
                        "Sugoi",
                        "Sultan Classic",
                        "Vagrant",
                        "V-STR",
                        "Drift Yosemite",
                        "Zhaba",
                        "Club",
                        "Coquette D10",
                        "Beater Dukes",
                        "Gauntlet Classic Custom",
                        "Glendale Custom",
                        "Landstalker XL",
                        "Manana Custom",
                        "BR8",
                        "DR1",
                        "Penumbra FF",
                        "Peyote Custom",
                        "Seminole Frontier",
                        "Tigon",
                        "Yosemite Rancher",
                        "Youga Classic 4x4",
                        "Veto Modern",
                        "Squaddie",
                        "Weaponized Dinghy",
                        "Annihilator Stealth",
                        "Itali RSX",
                        "Veto Classic",
                        "Toreador",
                        "Slamtruck",
                        "Weevil",
                        "Vetir",
                        "RO-86 Alkonost",
                        "Kurtz 31 Patrol Boat",
                        "Avisa",
                        "Brioso 300",
                        "Verus",
                        "Longfin",
                        "Sparrow",
                        "Sparrow",
                        "Winky",
                        "Manchez Scout",
                        "Kosatka",
                        "Freight Train",
                        "Comet S2",
                        "Dominator ASP",
                        "Dominator GTT",
                        "Euros",
                        "Futo GTX",
                        "RT3000",
                        "Sultan RS Classic",
                        "Tailgater S",
                        "Growler",
                        "Vectre",
                        "Remus",
                        "Calico GTF",
                        "Cypher",
                        "Jester RR",
                        "ZR350",
                        "Previon",
                        "Warrener HKR",
                        "Shinobi",
                        "Reever",
                        "Champion",
                        "Cinquemila",
                        "I-Wagen",
                        "Astron",
                        "Baller ST",
                        "Buffalo STX",
                        "Comet S2 Cabrio",
                        "Deity",
                        "Ignus",
                        "Jubilee",
                        "Patriot Mil-Spec",
                        "Zeno",
                        "Granger 3600LX",
                        "Youga Custom",
                        "Mule",
                        "Omnis e-GT",
                        "Sentinel Classic Widebody",
                        "Ruiner ZZ-8",
                        "Brioso 300 Widebody",
                        "Corsita",
                        "Draugur",
                        "Kanjo SJ",
                        "Postlude",
                        "Torero XO",
                        "Vigero ZX",
                        "LM87",
                        "10F",
                        "10F Widebody",
                        "Rhinehart",
                        "Conada",
                        "Greenwood",
                        "SM722",
                        "Weevil Custom"
                    },
                    new string[] {
                        "ninef",
                        "ninef2",
                        "blista",
                        "asea",
                        "asea2",
                        "boattrailer",
                        "bus",
                        "armytanker",
                        "armytrailer",
                        "armytrailer2",
                        "freighttrailer",
                        "coach",
                        "airbus",
                        "asterope",
                        "airtug",
                        "ambulance",
                        "barracks",
                        "barracks2",
                        "baller",
                        "baller2",
                        "bjxl",
                        "banshee",
                        "benson",
                        "bfinjection",
                        "biff",
                        "blazer",
                        "blazer2",
                        "blazer3",
                        "bison",
                        "bison2",
                        "bison3",
                        "boxville",
                        "boxville2",
                        "boxville3",
                        "bobcatxl",
                        "bodhi2",
                        "buccaneer",
                        "buffalo",
                        "buffalo2",
                        "bulldozer",
                        "bullet",
                        "blimp",
                        "burrito",
                        "burrito2",
                        "burrito3",
                        "burrito4",
                        "burrito5",
                        "cavalcade",
                        "cavalcade2",
                        "policet",
                        "gburrito",
                        "cablecar",
                        "caddy",
                        "caddy2",
                        "camper",
                        "carbonizzare",
                        "cheetah",
                        "comet2",
                        "cogcabrio",
                        "coquette",
                        "cutter",
                        "gresley",
                        "dilettante",
                        "dilettante2",
                        "dune",
                        "dune2",
                        "hotknife",
                        "dloader",
                        "dubsta",
                        "dubsta2",
                        "dump",
                        "rubble",
                        "docktug",
                        "dominator",
                        "emperor",
                        "emperor2",
                        "emperor3",
                        "entityxf",
                        "exemplar",
                        "elegy2",
                        "f620",
                        "fbi",
                        "fbi2",
                        "felon",
                        "felon2",
                        "feltzer2",
                        "firetruk",
                        "flatbed",
                        "forklift",
                        "fq2",
                        "fusilade",
                        "fugitive",
                        "futo",
                        "granger",
                        "gauntlet",
                        "habanero",
                        "hauler",
                        "handler",
                        "infernus",
                        "ingot",
                        "intruder",
                        "issi2",
                        "Jackal",
                        "journey",
                        "jb700",
                        "khamelion",
                        "landstalker",
                        "lguard",
                        "manana",
                        "mesa",
                        "mesa2",
                        "mesa3",
                        "crusader",
                        "minivan",
                        "mixer",
                        "mixer2",
                        "monroe",
                        "mower",
                        "mule",
                        "mule2",
                        "oracle",
                        "oracle2",
                        "packer",
                        "patriot",
                        "pbus",
                        "penumbra",
                        "peyote",
                        "phantom",
                        "phoenix",
                        "picador",
                        "pounder",
                        "police",
                        "police4",
                        "police2",
                        "police3",
                        "policeold1",
                        "policeold2",
                        "pony",
                        "pony2",
                        "prairie",
                        "pranger",
                        "premier",
                        "primo",
                        "proptrailer",
                        "rancherxl",
                        "rancherxl2",
                        "rapidgt",
                        "rapidgt2",
                        "radi",
                        "ratloader",
                        "rebel",
                        "regina",
                        "rebel2",
                        "rentalbus",
                        "ruiner",
                        "rumpo",
                        "rumpo2",
                        "rhino",
                        "riot",
                        "ripley",
                        "rocoto",
                        "romero",
                        "sabregt",
                        "sadler",
                        "sadler2",
                        "sandking",
                        "sandking2",
                        "schafter2",
                        "schwarzer",
                        "scrap",
                        "seminole",
                        "sentinel",
                        "sentinel2",
                        "zion",
                        "zion2",
                        "serrano",
                        "sheriff",
                        "sheriff2",
                        "speedo",
                        "speedo2",
                        "stanier",
                        "stinger",
                        "stingergt",
                        "stockade",
                        "stockade3",
                        "stratum",
                        "sultan",
                        "superd",
                        "surano",
                        "surfer",
                        "surfer2",
                        "surge",
                        "taco",
                        "tailgater",
                        "taxi",
                        "trash",
                        "tractor",
                        "tractor2",
                        "tractor3",
                        "graintrailer",
                        "baletrailer",
                        "tiptruck",
                        "tiptruck2",
                        "tornado",
                        "tornado2",
                        "tornado3",
                        "tornado4",
                        "tourbus",
                        "towtruck",
                        "towtruck2",
                        "utillitruck",
                        "utillitruck2",
                        "utillitruck3",
                        "voodoo2",
                        "washington",
                        "stretch",
                        "youga",
                        "ztype",
                        "sanchez",
                        "sanchez2",
                        "scorcher",
                        "tribike",
                        "tribike2",
                        "tribike3",
                        "fixter",
                        "cruiser",
                        "BMX",
                        "policeb",
                        "akuma",
                        "carbonrs",
                        "bagger",
                        "bati",
                        "bati2",
                        "ruffian",
                        "daemon",
                        "double",
                        "pcj",
                        "vader",
                        "vigero",
                        "faggio2",
                        "hexer",
                        "annihilator",
                        "buzzard",
                        "buzzard2",
                        "cargobob",
                        "cargobob2",
                        "cargobob3",
                        "skylift",
                        "polmav",
                        "maverick",
                        "nemesis",
                        "frogger",
                        "frogger2",
                        "cuban800",
                        "duster",
                        "stunt",
                        "mammatus",
                        "jet",
                        "shamal",
                        "luxor",
                        "titan",
                        "lazer",
                        "cargoplane",
                        "squalo",
                        "marquis",
                        "dinghy",
                        "dinghy2",
                        "jetmax",
                        "predator",
                        "tropic",
                        "seashark",
                        "seashark2",
                        "submersible",
                        "freightcar",
                        "freight",
                        "freightcont1",
                        "freightcont2",
                        "freightgrain",
                        "tankercar",
                        "metrotrain",
                        "docktrailer",
                        "trailers",
                        "trailers2",
                        "trailers3",
                        "tvtrailer",
                        "raketrailer",
                        "tanker",
                        "trailerlogs",
                        "tr2",
                        "tr3",
                        "tr4",
                        "trflat",
                        "trailersmall",
                        "velum",
                        "adder",
                        "voltic",
                        "vacca",
                        "suntrap",
                        "submersible2",
                        "dukes",
                        "dukes2",
                        "buffalo3",
                        "dominator2",
                        "dodo",
                        "marshall",
                        "blimp2",
                        "gauntlet2",
                        "stalion",
                        "stalion2",
                        "blista2",
                        "blista3",
                        "bifta",
                        "speeder",
                        "kalahari",
                        "paradise",
                        "btype",
                        "jester",
                        "turismor",
                        "alpha",
                        "vestra",
                        "zentorno",
                        "massacro",
                        "huntley",
                        "thrust",
                        "rhapsody",
                        "warrener",
                        "blade",
                        "glendale",
                        "panto",
                        "dubsta3",
                        "pigalle",
                        "monster",
                        "sovereign",
                        "innovation",
                        "hakuchou",
                        "furoregt",
                        "miljet",
                        "besra",
                        "coquette2",
                        "swift",
                        "jester2",
                        "massacro2",
                        "ratloader2",
                        "slamvan",
                        "mule3",
                        "velum2",
                        "tanker2",
                        "casco",
                        "boxville4",
                        "hydra",
                        "insurgent",
                        "insurgent2",
                        "gburrito2",
                        "technical",
                        "dinghy3",
                        "savage",
                        "enduro",
                        "guardian",
                        "lectro",
                        "kuruma",
                        "kuruma2",
                        "trash2",
                        "barracks3",
                        "valkyrie",
                        "slamvan2",
                        "swift2",
                        "luxor2",
                        "feltzer3",
                        "osiris",
                        "virgo",
                        "windsor",
                        "coquette3",
                        "vindicator",
                        "t20",
                        "brawler",
                        "toro",
                        "chino",
                        "faction",
                        "faction2",
                        "moonbeam",
                        "moonbeam2",
                        "primo2",
                        "chino2",
                        "buccaneer2",
                        "voodoo",
                        "Lurcher",
                        "btype2",
                        "verlierer2",
                        "nightshade",
                        "mamba",
                        "limo2",
                        "schafter3",
                        "schafter4",
                        "schafter5",
                        "schafter6",
                        "cog55",
                        "cog552",
                        "cognoscenti",
                        "cognoscenti2",
                        "baller3",
                        "baller4",
                        "baller5",
                        "baller6",
                        "toro2",
                        "seashark3",
                        "dinghy4",
                        "tropic2",
                        "speeder2",
                        "cargobob4",
                        "supervolito",
                        "supervolito2",
                        "valkyrie2",
                        "tampa",
                        "sultanrs",
                        "banshee2",
                        "btype3",
                        "faction3",
                        "minivan2",
                        "sabregt2",
                        "slamvan3",
                        "tornado5",
                        "virgo2",
                        "virgo3",
                        "nimbus",
                        "xls",
                        "xls2",
                        "seven70",
                        "fmj",
                        "bestiagts",
                        "pfister811",
                        "brickade",
                        "rumpo3",
                        "volatus",
                        "prototipo",
                        "reaper",
                        "tug",
                        "windsor2",
                        "lynx",
                        "gargoyle",
                        "tyrus",
                        "sheava",
                        "omnis",
                        "le7b",
                        "contender",
                        "trophytruck",
                        "trophytruck2",
                        "rallytruck",
                        "cliffhanger",
                        "bf400",
                        "tropos",
                        "brioso",
                        "tampa2",
                        "tornado6",
                        "faggio3",
                        "faggio",
                        "raptor",
                        "vortex",
                        "avarus",
                        "sanctus",
                        "youga2",
                        "hakuchou2",
                        "nightblade",
                        "chimera",
                        "esskey",
                        "wolfsbane",
                        "zombiea",
                        "zombieb",
                        "defiler",
                        "daemon2",
                        "ratbike",
                        "shotaro",
                        "manchez",
                        "blazer4",
                        "elegy",
                        "tempesta",
                        "italigtb",
                        "italigtb2",
                        "nero",
                        "nero2",
                        "specter",
                        "specter2",
                        "diablous",
                        "diablous2",
                        "blazer5",
                        "ruiner2",
                        "dune4",
                        "dune5",
                        "phantom2",
                        "voltic2",
                        "penetrator",
                        "boxville5",
                        "wastelander",
                        "technical2",
                        "fcr",
                        "fcr2",
                        "comet3",
                        "ruiner3",
                        "turismo2",
                        "infernus2",
                        "gp1",
                        "ruston",
                        "trailers4",
                        "xa21",
                        "caddy3",
                        "vagner",
                        "phantom3",
                        "nightshark",
                        "cheetah2",
                        "torero",
                        "hauler2",
                        "trailerlarge",
                        "technical3",
                        "insurgent3",
                        "apc",
                        "tampa3",
                        "dune3",
                        "trailersmall2",
                        "halftrack",
                        "ardent",
                        "oppressor",
                        "vigilante",
                        "bombushka",
                        "alphaz1",
                        "seabreeze",
                        "tula",
                        "havok",
                        "hunter",
                        "microlight",
                        "rogue",
                        "pyro",
                        "howard",
                        "mogul",
                        "starling",
                        "nokota",
                        "molotok",
                        "rapidgt3",
                        "retinue",
                        "cyclone",
                        "visione",
                        "z190",
                        "viseris",
                        "comet5",
                        "raiden",
                        "riata",
                        "sc1",
                        "autarch",
                        "savestra",
                        "gt500",
                        "comet4",
                        "neon",
                        "sentinel3",
                        "khanjali",
                        "barrage",
                        "volatol",
                        "akula",
                        "deluxo",
                        "stromberg",
                        "chernobog",
                        "riot2",
                        "avenger",
                        "avenger2",
                        "thruster",
                        "yosemite",
                        "hermes",
                        "hustler",
                        "streiter",
                        "revolter",
                        "pariah",
                        "kamacho",
                        "entity2",
                        "cheburek",
                        "jester3",
                        "caracara",
                        "hotring",
                        "seasparrow",
                        "flashgt",
                        "ellie",
                        "michelli",
                        "fagaloa",
                        "dominator3",
                        "tyrant",
                        "tezeract",
                        "gb200",
                        "issi3",
                        "taipan",
                        "blimp3",
                        "mule4",
                        "pounder2",
                        "speedo4",
                        "pbus2",
                        "patriot2",
                        "swinger",
                        "terbyte",
                        "oppressor2",
                        "strikeforce",
                        "menacer",
                        "scramjet",
                        "freecrawler",
                        "stafford",
                        "bruiser",
                        "bruiser2",
                        "bruiser3",
                        "brutus",
                        "brutus2",
                        "brutus3",
                        "cerberus",
                        "cerberus2",
                        "cerberus3",
                        "clique",
                        "deathbike",
                        "deathbike2",
                        "deathbike3",
                        "deveste",
                        "deviant",
                        "dominator4",
                        "dominator5",
                        "dominator6",
                        "impaler",
                        "impaler2",
                        "impaler3",
                        "impaler4",
                        "imperator",
                        "imperator2",
                        "imperator3",
                        "issi4",
                        "issi5",
                        "issi6",
                        "italigto",
                        "monster3",
                        "monster4",
                        "monster5",
                        "rcbandito",
                        "scarab",
                        "scarab2",
                        "scarab3",
                        "schlagen",
                        "slamvan4",
                        "slamvan5",
                        "slamvan6",
                        "toros",
                        "tulip",
                        "vamos",
                        "zr380",
                        "zr3802",
                        "zr3803",
                        "caracara2",
                        "drafter",
                        "dynasty",
                        "emerus",
                        "gauntlet3",
                        "gauntlet4",
                        "hellion",
                        "issi7",
                        "jugular",
                        "krieger",
                        "locust",
                        "paragon",
                        "paragon2",
                        "peyote2",
                        "nebula",
                        "neo",
                        "novak",
                        "rrocket",
                        "s80",
                        "thrax",
                        "zion3",
                        "zorrusso",
                        "asbo",
                        "formula2",
                        "formula",
                        "furia",
                        "imorgon",
                        "jb7002",
                        "kanjo",
                        "komoda",
                        "minitank",
                        "outlaw",
                        "rebla",
                        "retinue2",
                        "stryder",
                        "sugoi",
                        "sultan2",
                        "vagrant",
                        "vstr",
                        "yosemite2",
                        "zhaba",
                        "club",
                        "coquette4",
                        "dukes3",
                        "gauntlet5",
                        "glendale2",
                        "landstalker2",
                        "manana2",
                        "openwheel1",
                        "openwheel2",
                        "penumbra2",
                        "peyote3",
                        "seminole2",
                        "tigon",
                        "yosemite3",
                        "youga3",
                        "veto2",
                        "squaddie",
                        "dinghy5",
                        "annihilator2",
                        "italirsx",
                        "veto",
                        "toreador",
                        "slamtruck",
                        "weevil",
                        "vetir",
                        "alkonost",
                        "patrolboat",
                        "avisa",
                        "brioso2",
                        "verus",
                        "longfin",
                        "seasparrow2",
                        "seasparrow3",
                        "winky",
                        "manchez2",
                        "kosatka",
                        "freightcar2",
                        "comet6",
                        "dominator7",
                        "dominator8",
                        "euros",
                        "futo2",
                        "rt3000",
                        "sultan3",
                        "tailgater2",
                        "growler",
                        "vectre",
                        "remus",
                        "calico",
                        "cypher",
                        "jester4",
                        "zr350",
                        "previon",
                        "warrener2",
                        "shinobi",
                        "reever",
                        "champion",
                        "cinquemila",
                        "iwagen",
                        "astron",
                        "baller7",
                        "buffalo4",
                        "comet7",
                        "deity",
                        "ignus",
                        "jubilee",
                        "patriot3",
                        "zeno",
                        "granger2",
                        "youga4",
                        "mule5",
                        "omnisegt",
                        "sentinel4",
                        "ruiner4",
                        "brioso3",
                        "corsita",
                        "draugur",
                        "kanjosj",
                        "postlude",
                        "torero2",
                        "vigero2",
                        "lm87",
                        "tenf",
                        "tenf2",
                        "rhinehart",
                        "conada",
                        "greenwood",
                        "sm722",
                        "weevil2"
                    },
                },
            };

        public static Dictionary<string, string> mercedesVehicles = new Dictionary<string, string>()
        {

        };
    }
}
